name: SampleEnv
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - mlflow
    - matplotlib
    - seaborn
    - sklearn
    - azureml-mlflow
    - azureml-dataprep